// Deutsch A1 — расширенная база карточек
// Категории: Nomen / Verben / Sonstige
// Добавлены точные формы Präteritum и Perfekt для ich для всех глаголов

const wordsData = [
    // --- NOMEN (Существительные) ---
    {"de": "der Alltag", "pl": "Sg.", "ru": "будни, повседневность", "category": "Nomen"},
    {"de": "das Alphabet", "pl": "-e", "ru": "алфавит", "category": "Nomen"},
    {"de": "die Antwort", "pl": "-en", "ru": "ответ", "category": "Nomen"},
    {"de": "das Beispiel", "pl": "-e", "ru": "пример", "category": "Nomen"},
    {"de": "der Beruf", "pl": "-e", "ru": "профессия, специальность", "category": "Nomen"},
    {"de": "das Deutsch", "pl": "Sg.", "ru": "немецкий язык", "category": "Nomen"},
    {"de": "die Entschuldigung", "pl": "-en", "ru": "извинение", "category": "Nomen"},
    {"de": "der Familienname", "pl": "-en", "ru": "фамилия", "category": "Nomen"},
    {"de": "die Frage", "pl": "-n", "ru": "вопрос", "category": "Nomen"},
    {"de": "die Frau", "pl": "-en", "ru": "женщина, госпожа", "category": "Nomen"},
    {"de": "der Herr", "pl": "-en", "ru": "господин, мужчина", "category": "Nomen"},
    {"de": "der Kurs", "pl": "-e", "ru": "курс", "category": "Nomen"},
    {"de": "der Kursleiter", "pl": "-", "ru": "преподаватель, руководитель курса", "category": "Nomen"},
    {"de": "die Kursleiterin", "pl": "-nen", "ru": "преподавательница, руководительница курса", "category": "Nomen"},
    {"de": "das Land", "pl": "\"-er", "ru": "страна", "category": "Nomen"},
    {"de": "die Leute", "pl": "Pl.", "ru": "люди", "category": "Nomen"},
    {"de": "der Nachbar", "pl": "-n", "ru": "сосед", "category": "Nomen"},
    {"de": "die Nachbarin", "pl": "-nen", "ru": "соседка", "category": "Nomen"},
    {"de": "der Name", "pl": "-n", "ru": "имя, фамилия", "category": "Nomen"},
    {"de": "die Person", "pl": "-en", "ru": "человек, персона", "category": "Nomen"},
    {"de": "der Satz", "pl": "\"-e", "ru": "предложение", "category": "Nomen"},
    {"de": "die Sprache", "pl": "-n", "ru": "язык", "category": "Nomen"},
    {"de": "die Stadt", "pl": "\"-e", "ru": "город", "category": "Nomen"},
    {"de": "der Vorname", "pl": "-n", "ru": "имя", "category": "Nomen"},
    {"de": "die Adresse", "pl": "-n", "ru": "адрес", "category": "Nomen"},
    {"de": "die E-Mail-Adresse", "pl": "-n", "ru": "адрес электронной почты", "category": "Nomen"},
    {"de": "das Café", "pl": "-s", "ru": "кафе", "category": "Nomen"},
    {"de": "das Getränk", "pl": "-e", "ru": "напиток", "category": "Nomen"},
    {"de": "der Kaffee", "pl": "-s", "ru": "кофе", "category": "Nomen"},
    {"de": "die Kasse", "pl": "-n", "ru": "касса", "category": "Nomen"},
    {"de": "der Lehrer", "pl": "-", "ru": "учитель", "category": "Nomen"},
    {"de": "die Lehrerin", "pl": "-nen", "ru": "учительница", "category": "Nomen"},
    {"de": "die Milch", "pl": "Sg.", "ru": "молоко", "category": "Nomen"},
    {"de": "das Mineralwasser", "pl": "-", "ru": "минеральная вода", "category": "Nomen"},
    {"de": "die Nummer", "pl": "-n", "ru": "номер", "category": "Nomen"},
    {"de": "die Postleitzahl", "pl": "-en", "ru": "почтовый индекс", "category": "Nomen"},
    {"de": "der Student", "pl": "-en", "ru": "студент", "category": "Nomen"},
    {"de": "die Studentin", "pl": "-nen", "ru": "студентка", "category": "Nomen"},
    {"de": "die Stunde", "pl": "-n", "ru": "час, урок", "category": "Nomen"},
    {"de": "der Saft", "pl": "\"-e", "ru": "сок", "category": "Nomen"},
    {"de": "der Tee", "pl": "Sg.", "ru": "чай", "category": "Nomen"},
    {"de": "das Telefon", "pl": "-e", "ru": "телефон", "category": "Nomen"},
    {"de": "die Telefonnummer", "pl": "-n", "ru": "номер телефона", "category": "Nomen"},
    {"de": "die Vorwahl", "pl": "-en", "ru": "телефонный код города/страны", "category": "Nomen"},
    {"de": "das Wasser", "pl": "Sg.", "ru": "вода", "category": "Nomen"},
    {"de": "das Wochenende", "pl": "-n", "ru": "выходные", "category": "Nomen"},
    {"de": "das Wort", "pl": "\"-er", "ru": "слово", "category": "Nomen"},
    {"de": "der Zucker", "pl": "Sg.", "ru": "сахар", "category": "Nomen"},
    {"de": "der Bleistift", "pl": "-e", "ru": "карандаш", "category": "Nomen"},
    {"de": "die Brille", "pl": "-n", "ru": "очки", "category": "Nomen"},
    {"de": "das Buch", "pl": "\"-er", "ru": "книга", "category": "Nomen"},
    {"de": "der Computer", "pl": "-", "ru": "компьютер", "category": "Nomen"},
    {"de": "das Fahrrad", "pl": "\"-er", "ru": "велосипед", "category": "Nomen"},
    {"de": "der Fernseher", "pl": "-", "ru": "телевизор", "category": "Nomen"},
    {"de": "der Gegenstand", "pl": "\"-e", "ru": "предмет, вещь", "category": "Nomen"},
    {"de": "das Heft", "pl": "-e", "ru": "тетрадь", "category": "Nomen"},
    {"de": "der Kugelschreiber", "pl": "-", "ru": "шариковая ручка", "category": "Nomen"},
    {"de": "der Kühlschrank", "pl": "\"-e", "ru": "холодильник", "category": "Nomen"},
    {"de": "der Kunde", "pl": "-n", "ru": "клиент, покупатель", "category": "Nomen"},
    {"de": "die Kundin", "pl": "-nen", "ru": "клиентка, покупательница", "category": "Nomen"},
    {"de": "der Preis", "pl": "-e", "ru": "цена", "category": "Nomen"},
    {"de": "die Schere", "pl": "-n", "ru": "ножницы", "category": "Nomen"},
    {"de": "der Schrank", "pl": "\"-e", "ru": "шкаф", "category": "Nomen"},
    {"de": "der Verkäufer", "pl": "-", "ru": "продавец", "category": "Nomen"},
    {"de": "die Verkäuferin", "pl": "-nen", "ru": "продавщица", "category": "Nomen"},
    {"de": "das Wörterbuch", "pl": "\"-er", "ru": "словарь", "category": "Nomen"},
    {"de": "der Abend", "pl": "-e", "ru": "вечер", "category": "Nomen"},
    {"de": "die Arbeit", "pl": "Sg.", "ru": "работа", "category": "Nomen"},
    {"de": "die Bäckerei", "pl": "-en", "ru": "пекарня, булочная", "category": "Nomen"},
    {"de": "das Bad", "pl": "\"-er", "ru": "ванная комната, купальня", "category": "Nomen"},
    {"de": "das Brötchen", "pl": "-", "ru": "булочка", "category": "Nomen"},
    {"de": "der Chef", "pl": "-s", "ru": "шеф, начальник", "category": "Nomen"},
    {"de": "die Chefin", "pl": "-nen", "ru": "шеф, начальница", "category": "Nomen"},
    {"de": "der Eintritt", "pl": "Sg.", "ru": "вход, входная плата", "category": "Nomen"},
    {"de": "das Ende", "pl": "Sg.", "ru": "конец", "category": "Nomen"},
    {"de": "das Essen", "pl": "Sg.", "ru": "еда, прием пищи", "category": "Nomen"},
    {"de": "der Film", "pl": "-e", "ru": "фильм", "category": "Nomen"},
    {"de": "die Karte", "pl": "-n", "ru": "карта, билет, меню", "category": "Nomen"},
    {"de": "das Kino", "pl": "-s", "ru": "кинотеатр", "category": "Nomen"},
    {"de": "das Konzert", "pl": "-e", "ru": "концерт", "category": "Nomen"},
    {"de": "der Mittag", "pl": "-e", "ru": "полдень", "category": "Nomen"},
    {"de": "der Morgen", "pl": "-", "ru": "утро", "category": "Nomen"},
    {"de": "der Nachmittag", "pl": "-e", "ru": "время после полудня, день", "category": "Nomen"},
    {"de": "der Park", "pl": "-s", "ru": "парк", "category": "Nomen"},
    {"de": "die Pause", "pl": "-n", "ru": "перерыв", "category": "Nomen"},
    {"de": "die Schule", "pl": "-n", "ru": "школа", "category": "Nomen"},
    {"de": "das Schwimmbad", "pl": "\"-er", "ru": "бассейн", "category": "Nomen"},
    {"de": "der Tag", "pl": "-e", "ru": "день", "category": "Nomen"},
    {"de": "der Unterricht", "pl": "Sg.", "ru": "занятие, урок", "category": "Nomen"},
    {"de": "der Vormittag", "pl": "-e", "ru": "первая половина дня, до полудня", "category": "Nomen"},
    {"de": "die Woche", "pl": "-n", "ru": "неделя", "category": "Nomen"},
    {"de": "der Wochentag", "pl": "-e", "ru": "будний день, день недели", "category": "Nomen"},
    {"de": "die Zeit", "pl": "-en", "ru": "время", "category": "Nomen"},
    {"de": "die Zeitung", "pl": "-en", "ru": "газета", "category": "Nomen"},
    {"de": "der Apfel", "pl": "\"-", "ru": "яблоко", "category": "Nomen"},
    {"de": "das Bier", "pl": "-e", "ru": "пиво", "category": "Nomen"},
    {"de": "die Butter", "pl": "Sg.", "ru": "сливочное масло", "category": "Nomen"},
    {"de": "das Brot", "pl": "-e", "ru": "хлеб", "category": "Nomen"},
    {"de": "das Ei", "pl": "-er", "ru": "яйцо", "category": "Nomen"},
    {"de": "der Fisch", "pl": "-e", "ru": "рыба", "category": "Nomen"},
    {"de": "die Flasche", "pl": "-n", "ru": "бутылка", "category": "Nomen"},
    {"de": "das Fleisch", "pl": "Sg.", "ru": "мясо", "category": "Nomen"},
    {"de": "das Geld", "pl": "Sg.", "ru": "деньги", "category": "Nomen"},
    {"de": "das Gemüse", "pl": "-", "ru": "овощи", "category": "Nomen"},
    {"de": "das Gramm", "pl": "-e", "ru": "грамм", "category": "Nomen"},
    {"de": "die Kartoffel", "pl": "-n", "ru": "картофель", "category": "Nomen"},
    {"de": "der Käse", "pl": "Sg.", "ru": "сыр", "category": "Nomen"},
    {"de": "das Kilo(gramm)", "pl": "-s", "ru": "килограмм", "category": "Nomen"},
    {"de": "der Kuchen", "pl": "-", "ru": "пирог, выпечка", "category": "Nomen"},
    {"de": "der Laden", "pl": "\"-", "ru": "магазин", "category": "Nomen"},
    {"de": "das Lebensmittel", "pl": "-", "ru": "продукты питания", "category": "Nomen"},
    {"de": "der Liter", "pl": "-", "ru": "литр", "category": "Nomen"},
    {"de": "das Mehl", "pl": "Sg.", "ru": "мука", "category": "Nomen"},
    {"de": "das Obst", "pl": "Sg.", "ru": "фрукты", "category": "Nomen"},
    {"de": "das Öl", "pl": "-e", "ru": "растительное масло", "category": "Nomen"},
    {"de": "das Päckchen", "pl": "-", "ru": "пачка, небольшая упаковка", "category": "Nomen"},
    {"de": "das Paket", "pl": "-e", "ru": "пакет, посылка", "category": "Nomen"},
    {"de": "der Reis", "pl": "Sg.", "ru": "рис", "category": "Nomen"},
    {"de": "das Rezept", "pl": "-e", "ru": "рецепт", "category": "Nomen"},
    {"de": "der Salat", "pl": "-e", "ru": "салат", "category": "Nomen"},
    {"de": "das Salz", "pl": "Sg.", "ru": "соль", "category": "Nomen"},
    {"de": "der Schinken", "pl": "-", "ru": "ветчина", "category": "Nomen"},
    {"de": "das Schnitzel", "pl": "-", "ru": "шницель", "category": "Nomen"},
    {"de": "die Soße", "pl": "-n", "ru": "соус", "category": "Nomen"},
    {"de": "die Tüte", "pl": "-n", "ru": "пакет для продуктов", "category": "Nomen"},
    {"de": "der Wein", "pl": "-e", "ru": "вино", "category": "Nomen"},
    {"de": "die Wurst", "pl": "\"-e", "ru": "колбаса", "category": "Nomen"},
    {"de": "die Zwiebel", "pl": "-n", "ru": "репчатый лук", "category": "Nomen"},
    {"de": "der Ausflug", "pl": "\"-e", "ru": "экскурсия, поездка", "category": "Nomen"},
    {"de": "der Bruder", "pl": "\"-", "ru": "брат", "category": "Nomen"},
    {"de": "das Datum", "pl": "Sg.", "ru": "дата", "category": "Nomen"},
    {"de": "der Ehemann", "pl": "\"-er", "ru": "муж", "category": "Nomen"},
    {"de": "die Einladung", "pl": "-en", "ru": "приглашение", "category": "Nomen"},
    {"de": "das Fest", "pl": "-e", "ru": "праздник, торжество", "category": "Nomen"},
    {"de": "der Freund", "pl": "-e", "ru": "друг", "category": "Nomen"},
    {"de": "die Freundin", "pl": "-nen", "ru": "подруга", "category": "Nomen"},
    {"de": "der Frühling", "pl": "Sg.", "ru": "весна", "category": "Nomen"},
    {"de": "der Geburtstag", "pl": "-e", "ru": "день рождения", "category": "Nomen"},
    {"de": "das Geschenk", "pl": "-e", "ru": "подарок", "category": "Nomen"},
    {"de": "die Geschwister", "pl": "Pl.", "ru": "братья и сестры", "category": "Nomen"},
    {"de": "die Gesundheit", "pl": "Sg.", "ru": "здоровье", "category": "Nomen"},
    {"de": "das Glück", "pl": "Sg.", "ru": "счастье, удача", "category": "Nomen"},
    {"de": "der Glückwunsch", "pl": "\"-e", "ru": "поздравление", "category": "Nomen"},
    {"de": "die Großeltern", "pl": "Pl.", "ru": "бабушка и дедушка", "category": "Nomen"},
    {"de": "die Großmutter", "pl": "\"-", "ru": "бабушка", "category": "Nomen"},
    {"de": "der Großvater", "pl": "\"-", "ru": "дедушка", "category": "Nomen"},
    {"de": "der Haushalt", "pl": "-e", "ru": "домашнее хозяйство", "category": "Nomen"},
    {"de": "der Herbst", "pl": "Sg.", "ru": "осень", "category": "Nomen"},
    {"de": "die Hochzeit", "pl": "-en", "ru": "свадьба", "category": "Nomen"},
    {"de": "der Jugendliche", "pl": "-n", "ru": "подросток, юноша", "category": "Nomen"},
    {"de": "die Jugendliche", "pl": "-n", "ru": "подросток, девушка", "category": "Nomen"},
    {"de": "der Monat", "pl": "-e", "ru": "месяц", "category": "Nomen"},
    {"de": "die Mutter", "pl": "\"-", "ru": "мать", "category": "Nomen"},
    {"de": "der Onkel", "pl": "-", "ru": "дядя", "category": "Nomen"},
    {"de": "die Party", "pl": "-s", "ru": "вечеринка", "category": "Nomen"},
    {"de": "das Picknick", "pl": "-s", "ru": "пикник", "category": "Nomen"},
    {"de": "die Schwester", "pl": "-n", "ru": "сестра", "category": "Nomen"},
    {"de": "der Sommer", "pl": "Sg.", "ru": "лето", "category": "Nomen"},
    {"de": "die Tante", "pl": "-n", "ru": "тетя", "category": "Nomen"},
    {"de": "der Vater", "pl": "\"-", "ru": "отец", "category": "Nomen"},
    {"de": "der Verwandte", "pl": "-n", "ru": "родственник", "category": "Nomen"},
    {"de": "die Verwandte", "pl": "-n", "ru": "родственница", "category": "Nomen"},
    {"de": "der Winter", "pl": "Sg.", "ru": "зима", "category": "Nomen"},
    {"de": "die Ampel", "pl": "-n", "ru": "светофор", "category": "Nomen"},
    {"de": "die Anmeldung", "pl": "-en", "ru": "регистрация, запись", "category": "Nomen"},
    {"de": "die Auskunft", "pl": "\"-e", "ru": "справочная, справка", "category": "Nomen"},
    {"de": "der Ausweis", "pl": "-e", "ru": "удостоверение личности, паспорт", "category": "Nomen"},
    {"de": "die Bahn", "pl": "-en", "ru": "поезд, железная дорога", "category": "Nomen"},
    {"de": "der Bahnhof", "pl": "\"-e", "ru": "вокзал", "category": "Nomen"},
    {"de": "die Bank", "pl": "-en", "ru": "банк", "category": "Nomen"},
    {"de": "der Fahrplan", "pl": "\"-e", "ru": "расписание движения", "category": "Nomen"},
    {"de": "das Gehalt", "pl": "\"-er", "ru": "зарплата", "category": "Nomen"},
    {"de": "der Geldautomat", "pl": "-en", "ru": "банкомат", "category": "Nomen"},
    {"de": "das Girokonto", "pl": "-konten", "ru": "расчетный счет", "category": "Nomen"},
    {"de": "der Hauptbahnhof", "pl": "\"-e", "ru": "главный вокзал", "category": "Nomen"},
    {"de": "die Jugendherberge", "pl": "-n", "ru": "хостел для молодежи", "category": "Nomen"},
    {"de": "die Kantine", "pl": "-n", "ru": "столовая", "category": "Nomen"},
    {"de": "der Kilometer", "pl": "-", "ru": "километр", "category": "Nomen"},
    {"de": "die Kirche", "pl": "-n", "ru": "церковь", "category": "Nomen"},
    {"de": "die Kreuzung", "pl": "-en", "ru": "перекресток", "category": "Nomen"},
    {"de": "die Monatskarte", "pl": "-n", "ru": "проездной на месяц", "category": "Nomen"},
    {"de": "die Nähe", "pl": "Sg.", "ru": "близость, окрестность", "category": "Nomen"},
    {"de": "der Pass", "pl": "\"-e", "ru": "загранпаспорт", "category": "Nomen"},
    {"de": "das Personalbüro", "pl": "-s", "ru": "отдел кадров", "category": "Nomen"},
    {"de": "der Platz", "pl": "\"-e", "ru": "площадь, место", "category": "Nomen"},
    {"de": "die Richtung", "pl": "-en", "ru": "направление", "category": "Nomen"},
    {"de": "die S-Bahn", "pl": "-en", "ru": "городская электричка", "category": "Nomen"},
    {"de": "die Sparkasse", "pl": "-n", "ru": "сберкасса", "category": "Nomen"},
    {"de": "der Stadtplan", "pl": "\"-e", "ru": "карта города", "category": "Nomen"},
    {"de": "das Stadtzentrum", "pl": "-zentren", "ru": "центр города", "category": "Nomen"},
    {"de": "die Station", "pl": "-en", "ru": "станция, остановка", "category": "Nomen"},
    {"de": "die Straßenbahn", "pl": "-en", "ru": "трамвай", "category": "Nomen"},
    {"de": "das Taxi", "pl": "-s", "ru": "такси", "category": "Nomen"},
    {"de": "das Ticket", "pl": "-s", "ru": "билет", "category": "Nomen"},
    {"de": "der Tourist", "pl": "-en", "ru": "турист", "category": "Nomen"},
    {"de": "die Touristin", "pl": "-nen", "ru": "туристка", "category": "Nomen"},
    {"de": "die U-Bahn", "pl": "-en", "ru": "метро", "category": "Nomen"},
    {"de": "der Verkehr", "pl": "Sg.", "ru": "транспорт, движение", "category": "Nomen"},
    {"de": "der Weg", "pl": "-e", "ru": "дорога, путь", "category": "Nomen"},
    {"de": "der Zug", "pl": "\"-e", "ru": "поезд", "category": "Nomen"},
    {"de": "die Badewanne", "pl": "-n", "ru": "ванна", "category": "Nomen"},
    {"de": "der Balkon", "pl": "-e", "ru": "балкон", "category": "Nomen"},
    {"de": "die Dusche", "pl": "-n", "ru": "душ", "category": "Nomen"},
    {"de": "die Garage", "pl": "-n", "ru": "гараж", "category": "Nomen"},
    {"de": "der Garten", "pl": "\"-", "ru": "сад", "category": "Nomen"},
    {"de": "der Hausmeister", "pl": "-", "ru": "завхоз, хаусмайстер", "category": "Nomen"},
    {"de": "die Hausmeisterin", "pl": "-nen", "ru": "завхоз (женщина)", "category": "Nomen"},
    {"de": "der Hof", "pl": "\"-e", "ru": "двор", "category": "Nomen"},
    {"de": "die Kaution", "pl": "-en", "ru": "залог при аренде", "category": "Nomen"},
    {"de": "der Keller", "pl": "-", "ru": "подвал", "category": "Nomen"},
    {"de": "die Küche", "pl": "-n", "ru": "кухня", "category": "Nomen"},
    {"de": "der Lärm", "pl": "Sg.", "ru": "шум", "category": "Nomen"},
    {"de": "die Miete", "pl": "-n", "ru": "арендная плата", "category": "Nomen"},
    {"de": "die Möbel", "pl": "Pl.", "ru": "мебель", "category": "Nomen"},
    {"de": "der Müll", "pl": "Sg.", "ru": "мусор", "category": "Nomen"},
    {"de": "die Mülltonne", "pl": "-n", "ru": "мусорный бак", "category": "Nomen"},
    {"de": "die Nebenkosten", "pl": "Pl.", "ru": "коммунальные услуги", "category": "Nomen"},
    {"de": "der Parkplatz", "pl": "\"-e", "ru": "парковка, парковочное место", "category": "Nomen"},
    {"de": "die Ruhe", "pl": "Sg.", "ru": "тишина, покой", "category": "Nomen"},
    {"de": "der Schlüssel", "pl": "-", "ru": "ключ", "category": "Nomen"},
    {"de": "der Spielplatz", "pl": "\"-e", "ru": "детская площадка", "category": "Nomen"},
    {"de": "der Strom", "pl": "Sg.", "ru": "электричество, ток", "category": "Nomen"},
    {"de": "die Toilette", "pl": "-n", "ru": "туалет", "category": "Nomen"},
    {"de": "die Treppe", "pl": "-n", "ru": "лестница", "category": "Nomen"},
    {"de": "der Umzug", "pl": "\"-e", "ru": "переезд", "category": "Nomen"},
    {"de": "der Vermieter", "pl": "-", "ru": "арендодатель", "category": "Nomen"},
    {"de": "die Vermieterin", "pl": "-nen", "ru": "арендодательница", "category": "Nomen"},
    {"de": "das WC", "pl": "-s", "ru": "туалет", "category": "Nomen"},
    {"de": "das Wohnzimmer", "pl": "-", "ru": "гостиная", "category": "Nomen"},
    {"de": "die Arbeitsstelle", "pl": "-n", "ru": "место работы", "category": "Nomen"},
    {"de": "der Angestellte", "pl": "-n", "ru": "сотрудник, служащий", "category": "Nomen"},
    {"de": "die Angestellte", "pl": "-n", "ru": "сотрудница, служащая", "category": "Nomen"},
    {"de": "die Ausbildung", "pl": "-en", "ru": "профобучение, образование", "category": "Nomen"},
    {"de": "die Berufsausbildung", "pl": "-en", "ru": "профессиональное образование", "category": "Nomen"},
    {"de": "der Geburtsort", "pl": "-e", "ru": "место рождения", "category": "Nomen"},
    {"de": "die Geschichte", "pl": "Sg.", "ru": "история", "category": "Nomen"},
    {"de": "die Hauptstadt", "pl": "\"-e", "ru": "столица", "category": "Nomen"},
    {"de": "der Hunger", "pl": "Sg.", "ru": "голод", "category": "Nomen"},
    {"de": "die Idee", "pl": "-n", "ru": "идея, мысль", "category": "Nomen"},
    {"de": "der Kindergarten", "pl": "\"-", "ru": "детский сад", "category": "Nomen"},
    {"de": "das Krankenhaus", "pl": "\"-er", "ru": "больница", "category": "Nomen"},
    {"de": "der Krankenwagen", "pl": "-", "ru": "скорая помощь", "category": "Nomen"},
    {"de": "der Lehrgang", "pl": "\"-e", "ru": "учебный курс", "category": "Nomen"},
    {"de": "das Programm", "pl": "-e", "ru": "программа", "category": "Nomen"},
    {"de": "die Schulbildung", "pl": "Sg.", "ru": "школьное образование", "category": "Nomen"},
    {"de": "der Schluss", "pl": "\"-e", "ru": "конец, завершение", "category": "Nomen"},
    {"de": "der Test", "pl": "-s", "ru": "тест", "category": "Nomen"},
    {"de": "der Unfall", "pl": "\"-e", "ru": "несчастный случай, ДТП", "category": "Nomen"},
    {"de": "der Urlaub", "pl": "-e", "ru": "отпуск", "category": "Nomen"},
    {"de": "die Umschulung", "pl": "-en", "ru": "переквалификация", "category": "Nomen"},
    {"de": "der Wecker", "pl": "-", "ru": "будильник", "category": "Nomen"},
    {"de": "der Apparat", "pl": "-e", "ru": "аппарат, телефон", "category": "Nomen"},
    {"de": "der Arbeitsalltag", "pl": "Sg.", "ru": "трудовые будни", "category": "Nomen"},
    {"de": "die Arbeitszeit", "pl": "-en", "ru": "рабочее время", "category": "Nomen"},
    {"de": "der Betrieb", "pl": "-e", "ru": "предприятие, производство", "category": "Nomen"},
    {"de": "die Bewerbung", "pl": "-en", "ru": "резюме, заявка на работу", "category": "Nomen"},
    {"de": "die Bezahlung", "pl": "-en", "ru": "оплата", "category": "Nomen"},
    {"de": "die Erfahrung", "pl": "-en", "ru": "опыт", "category": "Nomen"},
    {"de": "der Fehler", "pl": "-", "ru": "ошибка", "category": "Nomen"},
    {"de": "der Führerschein", "pl": "-e", "ru": "водительские права", "category": "Nomen"},
    {"de": "die Großstadt", "pl": "\"-e", "ru": "крупный город", "category": "Nomen"},
    {"de": "die Hand", "pl": "\"-e", "ru": "рука, кисть", "category": "Nomen"},
    {"de": "der Job", "pl": "-s", "ru": "работа, подработка", "category": "Nomen"},
    {"de": "der Kellner", "pl": "-", "ru": "официант", "category": "Nomen"},
    {"de": "die Kellnerin", "pl": "-nen", "ru": "официантка", "category": "Nomen"},
    {"de": "der Künstler", "pl": "-", "ru": "художник, артист", "category": "Nomen"},
    {"de": "die Künstlerin", "pl": "-nen", "ru": "художница, артистка", "category": "Nomen"},
    {"de": "die Lohnabrechnung", "pl": "-en", "ru": "расчетный листок по зарплате", "category": "Nomen"},
    {"de": "der Mechaniker", "pl": "-", "ru": "механик", "category": "Nomen"},
    {"de": "die Mechanikerin", "pl": "-nen", "ru": "женщина-механик", "category": "Nomen"},
    {"de": "der Meister", "pl": "-", "ru": "мастер", "category": "Nomen"},
    {"de": "die Meisterin", "pl": "-nen", "ru": "мастер (женщина)", "category": "Nomen"},
    {"de": "der Mitarbeiter", "pl": "-", "ru": "сотрудник", "category": "Nomen"},
    {"de": "die Mitarbeiterin", "pl": "-nen", "ru": "сотрудница", "category": "Nomen"},
    {"de": "die Stadtmitte", "pl": "-n", "ru": "центр города", "category": "Nomen"},
    {"de": "die Stelle", "pl": "-n", "ru": "место работы, вакансия", "category": "Nomen"},
    {"de": "die Stellenanzeige", "pl": "-n", "ru": "объявление о вакансии", "category": "Nomen"},
    {"de": "der Stundenlohn", "pl": "\"-e", "ru": "почасовая оплата", "category": "Nomen"},
    {"de": "das Team", "pl": "-s", "ru": "команда, коллектив", "category": "Nomen"},
    {"de": "die Überstunde", "pl": "-n", "ru": "сверхурочный час", "category": "Nomen"},
    {"de": "die Voraussetzung", "pl": "-en", "ru": "условие, требование, предпосылка", "category": "Nomen"},
    {"de": "der Vorteil", "pl": "-e", "ru": "преимущество, выгода", "category": "Nomen"},
    {"de": "der Arm", "pl": "-e", "ru": "рука от кисти до плеча", "category": "Nomen"},
    {"de": "der Arzt", "pl": "\"-e", "ru": "врач, доктор", "category": "Nomen"},
    {"de": "die Ärztin", "pl": "-nen", "ru": "женщина-врач", "category": "Nomen"},
    {"de": "das Auge", "pl": "-n", "ru": "глаз", "category": "Nomen"},
    {"de": "der Bauch", "pl": "\"-e", "ru": "живот", "category": "Nomen"},
    {"de": "das Bein", "pl": "-e", "ru": "нога", "category": "Nomen"},
    {"de": "die Beschwerde", "pl": "-n", "ru": "жалоба, недомогание", "category": "Nomen"},
    {"de": "die Brust", "pl": "\"-e", "ru": "грудь", "category": "Nomen"},
    {"de": "der Doktor", "pl": "-en", "ru": "доктор, врач", "category": "Nomen"},
    {"de": "die Doktorin", "pl": "-nen", "ru": "доктор (женщина)", "category": "Nomen"},
    {"de": "das Fieber", "pl": "Sg.", "ru": "температура, жар", "category": "Nomen"},
    {"de": "das Gesicht", "pl": "-er", "ru": "лицо", "category": "Nomen"},
    {"de": "die Grippe", "pl": "Sg.", "ru": "грипп", "category": "Nomen"},
    {"de": "das Haar", "pl": "-e", "ru": "волос, волосы", "category": "Nomen"},
    {"de": "der Hals", "pl": "\"-e", "ru": "шея, горло", "category": "Nomen"},
    {"de": "die Haut", "pl": "Sg.", "ru": "кожа", "category": "Nomen"},
    {"de": "das Herz", "pl": "-en", "ru": "сердце", "category": "Nomen"},
    {"de": "der Husten", "pl": "Sg.", "ru": "кашель", "category": "Nomen"},
    {"de": "das Knie", "pl": "-", "ru": "колено", "category": "Nomen"},
    {"de": "der Kopf", "pl": "\"-e", "ru": "голова", "category": "Nomen"},
    {"de": "der Körper", "pl": "-", "ru": "тело, туловище", "category": "Nomen"},
    {"de": "die Mahlzeit", "pl": "-en", "ru": "прием пищи", "category": "Nomen"},
    {"de": "das Medikament", "pl": "-e", "ru": "лекарство, медикамент", "category": "Nomen"},
    {"de": "der Mund", "pl": "\"-er", "ru": "рот", "category": "Nomen"},
    {"de": "die Nase", "pl": "-n", "ru": "нос", "category": "Nomen"},
    {"de": "das Ohr", "pl": "-en", "ru": "ухо", "category": "Nomen"},
    {"de": "der Patient", "pl": "-en", "ru": "пациент", "category": "Nomen"},
    {"de": "die Patientin", "pl": "-nen", "ru": "пациентка", "category": "Nomen"},
    {"de": "der Rücken", "pl": "-", "ru": "спина", "category": "Nomen"},
    {"de": "die Salbe", "pl": "-n", "ru": "мазь", "category": "Nomen"},
    {"de": "der Schmerz", "pl": "-en", "ru": "боль", "category": "Nomen"},
    {"de": "der Schnupfen", "pl": "Sg.", "ru": "насморк", "category": "Nomen"},
    {"de": "der Spaziergang", "pl": "\"-e", "ru": "прогулка", "category": "Nomen"},
    {"de": "die Sprechstunde", "pl": "-n", "ru": "приемные часы врача", "category": "Nomen"},
    {"de": "die Tablette", "pl": "-n", "ru": "таблетка", "category": "Nomen"},
    {"de": "der Tropfen", "pl": "-", "ru": "капли", "category": "Nomen"},
    {"de": "der Zahn", "pl": "\"-e", "ru": "зуб", "category": "Nomen"},
    {"de": "die Ankunft", "pl": "Sg.", "ru": "прибытие, приезд", "category": "Nomen"},
    {"de": "der Aufzug", "pl": "\"-e", "ru": "лифт", "category": "Nomen"},
    {"de": "die Durchsage", "pl": "-n", "ru": "объявление по громкой связи", "category": "Nomen"},
    {"de": "das Einzelzimmer", "pl": "-", "ru": "одноместный номер", "category": "Nomen"},
    {"de": "die Fahrt", "pl": "-en", "ru": "поездка", "category": "Nomen"},
    {"de": "die Fahrkarte", "pl": "-n", "ru": "проездной билет", "category": "Nomen"},
    {"de": "das Fenster", "pl": "-", "ru": "окно", "category": "Nomen"},
    {"de": "der Flug", "pl": "\"-e", "ru": "полет, рейс", "category": "Nomen"},
    {"de": "der Flughafen", "pl": "\"-", "ru": "аэропорт", "category": "Nomen"},
    {"de": "das Flugzeug", "pl": "-e", "ru": "самолет", "category": "Nomen"},
    {"de": "die Freizeit", "pl": "Sg.", "ru": "свободное время, досуг", "category": "Nomen"},
    {"de": "der Gang", "pl": "\"-e", "ru": "проход между рядами, коридор", "category": "Nomen"},
    {"de": "das Gepäck", "pl": "Sg.", "ru": "багаж", "category": "Nomen"},
    {"de": "die Jahreszeit", "pl": "-en", "ru": "время года", "category": "Nomen"},
    {"de": "der Koffer", "pl": "-", "ru": "чемодан", "category": "Nomen"},
    {"de": "das Meer", "pl": "-e", "ru": "море", "category": "Nomen"},
    {"de": "die Pension", "pl": "-en", "ru": "пансионат, гостевой дом", "category": "Nomen"},
    {"de": "der Prospekt", "pl": "-e", "ru": "проспект, брошюра, буклет", "category": "Nomen"},
    {"de": "die Reise", "pl": "-n", "ru": "путешествие, поездка", "category": "Nomen"},
    {"de": "das Reisebüro", "pl": "-s", "ru": "турагентство", "category": "Nomen"},
    {"de": "die Rezeption", "pl": "-en", "ru": "стойка регистрации, ресепшен", "category": "Nomen"},
    {"de": "der Schnee", "pl": "Sg.", "ru": "снег", "category": "Nomen"},
    {"de": "der See", "pl": "-n", "ru": "озеро", "category": "Nomen"},
    {"de": "die Sonne", "pl": "Sg.", "ru": "солнце", "category": "Nomen"},
    {"de": "der Strand", "pl": "\"-e", "ru": "пляж", "category": "Nomen"},
    {"de": "die Übernachtung", "pl": "-en", "ru": "ночевка, проживание в отеле", "category": "Nomen"},
    {"de": "die Verbindung", "pl": "-en", "ru": "транспортное сообщение, соединение", "category": "Nomen"},
    {"de": "das Wetter", "pl": "Sg.", "ru": "погода", "category": "Nomen"},
    {"de": "der Wind", "pl": "-e", "ru": "ветер", "category": "Nomen"},
    {"de": "die Wolke", "pl": "-n", "ru": "облако, туча", "category": "Nomen"},

    // --- VERBEN (Глаголы с точными формами ich для Präteritum и Perfekt) ---
    {"de": "antworten", "pl": "—", "ru": "отвечать", "category": "Verben", "prat": "ich antwortete", "perf": "ich habe geantwortet"},
    {"de": "begrüßen", "pl": "—", "ru": "приветствовать", "category": "Verben", "prat": "ich begrüßte", "perf": "ich habe begrüßt"},
    {"de": "buchstabieren", "pl": "—", "ru": "читать по буквам", "category": "Verben", "prat": "ich buchstabierte", "perf": "ich habe buchstabiert"},
    {"de": "fragen", "pl": "—", "ru": "спрашивать", "category": "Verben", "prat": "ich fragte", "perf": "ich habe gefragt"},
    {"de": "haben", "pl": "—", "ru": "иметь", "category": "Verben", "prat": "ich hatte", "perf": "ich habe gehabt"},
    {"de": "heißen", "pl": "—", "ru": "называться, зваться", "category": "Verben", "prat": "ich hieß", "perf": "ich habe geheißen"},
    {"de": "hören", "pl": "—", "ru": "слушать, слышать", "category": "Verben", "prat": "ich hörte", "perf": "ich habe gehört"},
    {"de": "kommen", "pl": "—", "ru": "приходить, приезжать", "category": "Verben", "prat": "ich kam", "perf": "ich bin gekommen"},
    {"de": "lernen", "pl": "—", "ru": "учиться, учить", "category": "Verben", "prat": "ich lernte", "perf": "ich habe gelernt"},
    {"de": "lesen", "pl": "—", "ru": "читать", "category": "Verben", "prat": "ich las", "perf": "ich habe gelesen"},
    {"de": "machen", "pl": "—", "ru": "делать", "category": "Verben", "prat": "ich machte", "perf": "ich habe gemacht"},
    {"de": "schreiben", "pl": "—", "ru": "писать", "category": "Verben", "prat": "ich schrieb", "perf": "ich habe geschrieben"},
    {"de": "sein", "pl": "—", "ru": "быть", "category": "Verben", "prat": "ich war", "perf": "ich bin gewesen"},
    {"de": "sprechen", "pl": "—", "ru": "говорить, разговаривать", "category": "Verben", "prat": "ich sprach", "perf": "ich habe gesprochen"},
    {"de": "(sich) verabschieden", "pl": "—", "ru": "прощаться", "category": "Verben", "prat": "ich verabschiedete mich", "perf": "ich habe mich verabschiedet"},
    {"de": "verstehen", "pl": "—", "ru": "понимать", "category": "Verben", "prat": "ich verstand", "perf": "ich habe verstanden"},
    {"de": "(sich) vorstellen", "pl": "—", "ru": "представляться", "category": "Verben", "prat": "ich stellte mich vor", "perf": "ich habe mich vorgestellt"},
    {"de": "wohnen", "pl": "—", "ru": "жить, проживать", "category": "Verben", "prat": "ich wohnte", "perf": "ich habe gewohnt"},
    {"de": "anrufen", "pl": "—", "ru": "звонить по телефону", "category": "Verben", "prat": "ich rief an", "perf": "ich habe angerufen"},
    {"de": "arbeiten", "pl": "—", "ru": "работать", "category": "Verben", "prat": "ich arbeitete", "perf": "ich habe gearbeitet"},
    {"de": "erreichen", "pl": "—", "ru": "дозвониться, застать, достигать", "category": "Verben", "prat": "ich erreichte", "perf": "ich habe erreicht"},
    {"de": "fahren", "pl": "—", "ru": "ехать", "category": "Verben", "prat": "ich fuhr", "perf": "ich bin gefahren"},
    {"de": "gehen", "pl": "—", "ru": "идти", "category": "Verben", "prat": "ich ging", "perf": "ich bin gegangen"},
    {"de": "können", "pl": "—", "ru": "мочь, уметь", "category": "Verben", "prat": "ich konnte", "perf": "ich habe gekonnt"},
    {"de": "kosten", "pl": "—", "ru": "стоить", "category": "Verben", "prat": "ich kostete", "perf": "ich habe gekostet"},
    {"de": "markieren", "pl": "—", "ru": "отмечать, выделять", "category": "Verben", "prat": "ich markierte", "perf": "ich habe markiert"},
    {"de": "nehmen", "pl": "—", "ru": "брать", "category": "Verben", "prat": "ich nahm", "perf": "ich habe genommen"},
    {"de": "sagen", "pl": "—", "ru": "говорить, сказать", "category": "Verben", "prat": "ich sagte", "perf": "ich habe gesagt"},
    {"de": "trinken", "pl": "—", "ru": "пить", "category": "Verben", "prat": "ich trank", "perf": "ich habe getrunken"},
    {"de": "brauchen", "pl": "—", "ru": "нуждаться, требоваться", "category": "Verben", "prat": "ich brauchte", "perf": "ich habe gebraucht"},
    {"de": "einkaufen", "pl": "—", "ru": "делать покупки", "category": "Verben", "prat": "ich kaufte ein", "perf": "ich habe eingekauft"},
    {"de": "finden", "pl": "—", "ru": "находить, считать", "category": "Verben", "prat": "ich fand", "perf": "ich habe gefunden"},
    {"de": "geben", "pl": "—", "ru": "давать", "category": "Verben", "prat": "ich gab", "perf": "ich habe gegeben"},
    {"de": "kaufen", "pl": "—", "ru": "покупать", "category": "Verben", "prat": "ich kaufte", "perf": "ich habe gekauft"},
    {"de": "schauen", "pl": "—", "ru": "смотреть", "category": "Verben", "prat": "ich schaute", "perf": "ich habe geschaut"},
    {"de": "suchen", "pl": "—", "ru": "искать", "category": "Verben", "prat": "ich suchte", "perf": "ich habe gesucht"},
    {"de": "verkaufen", "pl": "—", "ru": "продавать", "category": "Verben", "prat": "ich verkaufte", "perf": "ich habe verkauft"},
    {"de": "zahlen", "pl": "—", "ru": "платить", "category": "Verben", "prat": "ich zahlte", "perf": "ich habe gezahlt"},
    {"de": "anfangen", "pl": "—", "ru": "начинать", "category": "Verben", "prat": "ich fing an", "perf": "ich habe angefangen"},
    {"de": "aufmachen", "pl": "—", "ru": "открывать", "category": "Verben", "prat": "ich machte auf", "perf": "ich habe aufgemacht"},
    {"de": "aufstehen", "pl": "—", "ru": "вставать", "category": "Verben", "prat": "ich stand auf", "perf": "ich bin aufgestanden"},
    {"de": "aufwachen", "pl": "—", "ru": "просыпаться", "category": "Verben", "prat": "ich wachte auf", "perf": "ich bin aufgewacht"},
    {"de": "ausmachen", "pl": "—", "ru": "выключать", "category": "Verben", "prat": "ich machte aus", "perf": "ich habe ausgemacht"},
    {"de": "beginnen", "pl": "—", "ru": "начинать", "category": "Verben", "prat": "ich begann", "perf": "ich habe begonnen"},
    {"de": "duschen", "pl": "—", "ru": "принимать душ", "category": "Verben", "prat": "ich duschte", "perf": "ich habe geduscht"},
    {"de": "einladen", "pl": "—", "ru": "приглашать", "category": "Verben", "prat": "ich lud ein", "perf": "ich habe eingeladen"},
    {"de": "einschlafen", "pl": "—", "ru": "засыпать", "category": "Verben", "prat": "ich schlief ein", "perf": "ich bin eingeschlafen"},
    {"de": "frühstücken", "pl": "—", "ru": "завтракать", "category": "Verben", "prat": "ich frühstückte", "perf": "ich habe gefrühstückt"},
    {"de": "sehen", "pl": "—", "ru": "смотреть, видеть", "category": "Verben", "prat": "ich sah", "perf": "ich habe gesehen"},
    {"de": "(sich) verabreden", "pl": "—", "ru": "договариваться о встрече", "category": "Verben", "prat": "ich verabredete mich", "perf": "ich habe mich verabredet"},
    {"de": "warten", "pl": "—", "ru": "ждать", "category": "Verben", "prat": "ich wartete", "perf": "ich habe gewartet"},
    {"de": "zumachen", "pl": "—", "ru": "закрывать", "category": "Verben", "prat": "ich machte zu", "perf": "ich habe zugemacht"},
    {"de": "bekommen", "pl": "—", "ru": "получать", "category": "Verben", "prat": "ich bekam", "perf": "ich habe bekommen"},
    {"de": "dürfen", "pl": "—", "ru": "мочь, иметь разрешение", "category": "Verben", "prat": "ich durfte", "perf": "ich habe gedurft"},
    {"de": "fehlen", "pl": "—", "ru": "отсутствовать, не хватать", "category": "Verben", "prat": "ich fehlte", "perf": "ich habe gefehlt"},
    {"de": "holen", "pl": "—", "ru": "приносить, брать", "category": "Verben", "prat": "ich holte", "perf": "ich habe geholt"},
    {"de": "legen", "pl": "—", "ru": "класть", "category": "Verben", "prat": "ich legte", "perf": "ich habe gelegt"},
    {"de": "kochen", "pl": "—", "ru": "варить, готовить", "category": "Verben", "prat": "ich kochte", "perf": "ich habe gekocht"},
    {"de": "braten", "pl": "—", "ru": "жарить", "category": "Verben", "prat": "ich briet", "perf": "ich habe gebraten"},
    {"de": "backen", "pl": "—", "ru": "печь", "category": "Verben", "prat": "ich buk / backte", "perf": "ich habe gebacken"},
    {"de": "mitbringen", "pl": "—", "ru": "приносить с собой", "category": "Verben", "prat": "ich brachte mit", "perf": "ich habe mitgebracht"},
    {"de": "schneiden", "pl": "—", "ru": "резать", "category": "Verben", "prat": "ich schnitt", "perf": "ich habe geschnitten"},
    {"de": "vergleichen", "pl": "—", "ru": "сравнивать", "category": "Verben", "prat": "ich verglich", "perf": "ich habe verglichen"},
    {"de": "waschen", "pl": "—", "ru": "мыть", "category": "Verben", "prat": "ich wusch", "perf": "ich habe gewaschen"},
    {"de": "wünschen", "pl": "—", "ru": "желать", "category": "Verben", "prat": "ich wünschte", "perf": "ich habe gewünscht"},
    {"de": "aussehen", "pl": "—", "ru": "выглядеть", "category": "Verben", "prat": "ich sah aus", "perf": "ich habe ausgesehen"},
    {"de": "besuchen", "pl": "—", "ru": "посещать, навещать", "category": "Verben", "prat": "ich besuchte", "perf": "ich habe besucht"},
    {"de": "erziehen", "pl": "—", "ru": "воспитывать", "category": "Verben", "prat": "ich erzog", "perf": "ich habe erzogen"},
    {"de": "feiern", "pl": "—", "ru": "праздновать, отмечать", "category": "Verben", "prat": "ich feierte", "perf": "ich habe gefeiert"},
    {"de": "(sich) freuen", "pl": "—", "ru": "радоваться", "category": "Verben", "prat": "ich freute mich", "perf": "ich habe mich gefreut"},
    {"de": "gratulieren", "pl": "—", "ru": "поздравлять", "category": "Verben", "prat": "ich gratulierte", "perf": "ich habe gratuliert"},
    {"de": "heiraten", "pl": "—", "ru": "жениться, выходить замуж", "category": "Verben", "prat": "ich heiratete", "perf": "ich habe geheiratet"},
    {"de": "leben", "pl": "—", "ru": "жить", "category": "Verben", "prat": "ich lebte", "perf": "ich habe gelebt"},
    {"de": "studieren", "pl": "—", "ru": "учиться в ВУЗе", "category": "Verben", "prat": "ich studierte", "perf": "ich habe studiert"},
    {"de": "tanzen", "pl": "—", "ru": "танцевать", "category": "Verben", "prat": "ich tanzte", "perf": "ich habe getanzt"},
    {"de": "ankommen", "pl": "—", "ru": "прибывать", "category": "Verben", "prat": "ich kam an", "perf": "ich bin angekommen"},
    {"de": "anschauen", "pl": "—", "ru": "рассматривать, смотреть", "category": "Verben", "prat": "ich schaute an", "perf": "ich habe angeschaut"},
    {"de": "aussteigen", "pl": "—", "ru": "выходить из транспорта", "category": "Verben", "prat": "ich stieg aus", "perf": "ich bin ausgestiegen"},
    {"de": "besichtigen", "pl": "—", "ru": "осматривать достопримечательности", "category": "Verben", "prat": "ich besichtigte", "perf": "ich habe besichtigt"},
    {"de": "erleben", "pl": "—", "ru": "переживать, испытывать", "category": "Verben", "prat": "ich erlebte", "perf": "ich habe erlebt"},
    {"de": "halten", "pl": "—", "ru": "останавливаться", "category": "Verben", "prat": "ich hielt", "perf": "ich habe gehalten"},
    {"de": "umsteigen", "pl": "—", "ru": "пересаживаться", "category": "Verben", "prat": "ich stieg um", "perf": "ich bin umgestiegen"},
    {"de": "ausziehen", "pl": "—", "ru": "выезжать из квартиры", "category": "Verben", "prat": "ich zog aus", "perf": "ich bin ausgezogen"},
    {"de": "beachten", "pl": "—", "ru": "обращать внимание, соблюдать", "category": "Verben", "prat": "ich beachtete", "perf": "ich habe beachtet"},
    {"de": "benutzen", "pl": "—", "ru": "использовать, пользоваться", "category": "Verben", "prat": "ich benutzte", "perf": "ich habe benutzt"},
    {"de": "bezahlen", "pl": "—", "ru": "оплачивать", "category": "Verben", "prat": "ich bezahlte", "perf": "ich habe bezahlt"},
    {"de": "einziehen", "pl": "—", "ru": "въезжать в квартиру", "category": "Verben", "prat": "ich zog ein", "perf": "ich bin eingezogen"},
    {"de": "informieren", "pl": "—", "ru": "информировать", "category": "Verben", "prat": "ich informierte", "perf": "ich habe informiert"},
    {"de": "mieten", "pl": "—", "ru": "снимать, арендовать", "category": "Verben", "prat": "ich mietete", "perf": "ich habe gemietet"},
    {"de": "packen", "pl": "—", "ru": "упаковывать", "category": "Verben", "prat": "ich packte", "perf": "ich habe gepackt"},
    {"de": "parken", "pl": "—", "ru": "парковаться", "category": "Verben", "prat": "ich parkte", "perf": "ich habe geparkt"},
    {"de": "reinigen", "pl": "—", "ru": "чистить, убирать", "category": "Verben", "prat": "ich reinigte", "perf": "ich habe gereinigt"},
    {"de": "sorgen", "pl": "—", "ru": "заботиться", "category": "Verben", "prat": "ich sorgte", "perf": "ich habe gesorgt"},
    {"de": "tragen", "pl": "—", "ru": "нести, носить", "category": "Verben", "prat": "ich trug", "perf": "ich habe getragen"},
    {"de": "trocknen", "pl": "—", "ru": "сушить", "category": "Verben", "prat": "ich trocknete", "perf": "ich habe getrocknet"},
    {"de": "umziehen", "pl": "—", "ru": "переезжать", "category": "Verben", "prat": "ich zog um", "perf": "ich bin umgezogen"},
    {"de": "unterschreiben", "pl": "—", "ru": "подписывать", "category": "Verben", "prat": "ich unterschrieb", "perf": "ich habe unterschrieben"},
    {"de": "verdienen", "pl": "—", "ru": "зарабатывать", "category": "Verben", "prat": "ich verdiente", "perf": "ich habe verdient"},
    {"de": "vermieten", "pl": "—", "ru": "сдавать в аренду", "category": "Verben", "prat": "ich vermietete", "perf": "ich habe vermietet"},
    {"de": "ausreisen", "pl": "—", "ru": "выезжать из страны", "category": "Verben", "prat": "ich reiste aus", "perf": "ich bin ausgereist"},
    {"de": "bleiben", "pl": "—", "ru": "оставаться", "category": "Verben", "prat": "ich blieb", "perf": "ich bin geblieben"},
    {"de": "dauern", "pl": "—", "ru": "длиться", "category": "Verben", "prat": "ich dauerte", "perf": "ich hat gedauert"},
    {"de": "fallen", "pl": "—", "ru": "падать", "category": "Verben", "prat": "ich fiel", "perf": "ich bin gefallen"},
    {"de": "korrigieren", "pl": "—", "ru": "исправлять", "category": "Verben", "prat": "ich korrigierte", "perf": "ich habe korrigiert"},
    {"de": "lachen", "pl": "—", "ru": "смеяться", "category": "Verben", "prat": "ich lachte", "perf": "ich habe gelacht"},
    {"de": "passieren", "pl": "—", "ru": "происходить", "category": "Verben", "prat": "es passierte", "perf": "es ist passiert"},
    {"de": "putzen", "pl": "—", "ru": "чистить", "category": "Verben", "prat": "ich putzte", "perf": "ich habe geputzt"},
    {"de": "renovieren", "pl": "—", "ru": "делать ремонт", "category": "Verben", "prat": "ich renovierte", "perf": "ich habe renoviert"},
    {"de": "rufen", "pl": "—", "ru": "звать, кричать, звонить", "category": "Verben", "prat": "ich rief", "perf": "ich habe gerufen"},
    {"de": "singen", "pl": "—", "ru": "петь", "category": "Verben", "prat": "ich sang", "perf": "ich habe gesungen"},
    {"de": "wegbringen", "pl": "—", "ru": "уносить, убирать", "category": "Verben", "prat": "ich brachte weg", "perf": "ich habe weggebracht"},
    {"de": "überlegen", "pl": "—", "ru": "размышлять, обдумывать", "category": "Verben", "prat": "ich überlegte", "perf": "ich habe überlegt"},
    {"de": "wählen", "pl": "—", "ru": "выбирать", "category": "Verben", "prat": "ich wählte", "perf": "ich habe gewählt"},
    {"de": "ziehen", "pl": "—", "ru": "тянуть, тащить", "category": "Verben", "prat": "ich zog", "perf": "ich habe gezogen"},
    {"de": "beraten", "pl": "—", "ru": "консультировать", "category": "Verben", "prat": "ich beriet", "perf": "ich habe beraten"},
    {"de": "bieten", "pl": "—", "ru": "предлагать", "category": "Verben", "prat": "ich bot", "perf": "ich habe geboten"},
    {"de": "dabeihaben", "pl": "—", "ru": "иметь при себе", "category": "Verben", "prat": "ich hatte dabei", "perf": "ich habe dabeigekabt"},
    {"de": "erfinden", "pl": "—", "ru": "изобретать", "category": "Verben", "prat": "ich erfand", "perf": "ich habe erfunden"},
    {"de": "nachschlagen", "pl": "—", "ru": "искать в словаре", "category": "Verben", "prat": "ich schlug nach", "perf": "ich habe nachgeschlagen"},
    {"de": "pflegen", "pl": "—", "ru": "ухаживать", "category": "Verben", "prat": "ich pflegte", "perf": "ich habe gepflegt"},
    {"de": "reagieren", "pl": "—", "ru": "реагировать", "category": "Verben", "prat": "ich reagierte", "perf": "ich habe reagiert"},
    {"de": "reparieren", "pl": "—", "ru": "ремонтировать", "category": "Verben", "prat": "ich reparierte", "perf": "ich habe repariert"},
    {"de": "verbinden", "pl": "—", "ru": "соединять по телефону", "category": "Verben", "prat": "ich verband", "perf": "ich habe verbunden"},
    {"de": "wechseln", "pl": "—", "ru": "менять, обменивать", "category": "Verben", "prat": "ich wechselte", "perf": "ich habe gewechselt"},
    {"de": "zusammenarbeiten", "pl": "—", "ru": "сотрудничать, работать вместе", "category": "Verben", "prat": "ich arbeitete zusammen", "perf": "ich habe zusammengearbeitet"},
    {"de": "abnehmen", "pl": "—", "ru": "худеть, сбрасывать вес", "category": "Verben", "prat": "ich nahm ab", "perf": "ich habe abgenommen"},
    {"de": "erlauben", "pl": "—", "ru": "разрешать, позволять", "category": "Verben", "prat": "ich erlaubte", "perf": "ich habe erlaubt"},
    {"de": "hinfallen", "pl": "—", "ru": "падать", "category": "Verben", "prat": "ich fiel hin", "perf": "ich bin hingefallen"},
    {"de": "spazieren gehen", "pl": "—", "ru": "гулять, идти гулять", "category": "Verben", "prat": "ich ging spazieren", "perf": "ich bin spazieren gegangen"},
    {"de": "untersuchen", "pl": "—", "ru": "обследовать, осматривать пациента", "category": "Verben", "prat": "ich untersuchte", "perf": "ich habe untersucht"},
    {"de": "wehtun", "pl": "—", "ru": "болеть, причинять боль", "category": "Verben", "prat": "es tat weh", "perf": "es hat wehgetan"},
    {"de": "wiederkommen", "pl": "—", "ru": "возвращаться, приходить снова", "category": "Verben", "prat": "ich kam wieder", "perf": "ich bin wiedergekommen"},
    {"de": "zunehmen", "pl": "—", "ru": "полнеть, набирать вес", "category": "Verben", "prat": "ich nahm zu", "perf": "ich habe zugenommen"},
    {"de": "abfliegen", "pl": "—", "ru": "вылетать", "category": "Verben", "prat": "ich flog ab", "perf": "ich bin abgeflogen"},
    {"de": "ausgeben", "pl": "—", "ru": "тратить деньги", "category": "Verben", "prat": "ich gab aus", "perf": "ich habe ausgegeben"},
    {"de": "buchen", "pl": "—", "ru": "бронировать", "category": "Verben", "prat": "ich buchte", "perf": "ich habe gebucht"},
    {"de": "einsteigen", "pl": "—", "ru": "садиться в транспорт", "category": "Verben", "prat": "ich stieg ein", "perf": "ich bin eingestiegen"},
    {"de": "empfehlen", "pl": "—", "ru": "рекомендовать, советовать", "category": "Verben", "prat": "ich empfahl", "perf": "ich habe empfohlen"},
    {"de": "fliegen", "pl": "—", "ru": "летать, лететь", "category": "Verben", "prat": "ich flog", "perf": "ich bin geflogen"},
    {"de": "mitfahren", "pl": "—", "ru": "ехать вместе", "category": "Verben", "prat": "ich fuhr mit", "perf": "ich bin mitgefahren"},
    {"de": "regnen", "pl": "—", "ru": "идти (о дожде)", "category": "Verben", "prat": "es regnete", "perf": "es hat geregnet"},
    {"de": "reisen", "pl": "—", "ru": "путешествовать", "category": "Verben", "prat": "ich reiste", "perf": "ich bin gereist"},
    {"de": "reservieren", "pl": "—", "ru": "резервировать, бронировать", "category": "Verben", "prat": "ich reservierte", "perf": "ich habe reserviert"},
    {"de": "scheinen", "pl": "—", "ru": "светить, казаться", "category": "Verben", "prat": "ich schien", "perf": "ich habe geschienen"},
    {"de": "schneien", "pl": "—", "ru": "идти (о снеге)", "category": "Verben", "prat": "es schneite", "perf": "es hat geschneit"},
    {"de": "sparen", "pl": "—", "ru": "копить, экономить", "category": "Verben", "prat": "ich sparte", "perf": "ich habe gespart"},
    {"de": "verreisen", "pl": "—", "ru": "уезжать в поездку", "category": "Verben", "prat": "ich verreiste", "perf": "ich bin verreist"},
    {"de": "wandern", "pl": "—", "ru": "ходить в пешие походы", "category": "Verben", "prat": "ich wanderte", "perf": "ich bin gewandert"},
    {"de": "zurückfahren", "pl": "—", "ru": "ехать обратно, возвращаться", "category": "Verben", "prat": "ich fuhr zurück", "perf": "ich bin zurückgefahren"},

    // --- SONSTIGE WÖRTER (Остальные слова) ---
    {"de": "frei", "pl": "—", "ru": "свободный", "category": "Sonstige"},
    {"de": "gut", "pl": "—", "ru": "хороший, хорошо", "category": "Sonstige"},
    {"de": "müde", "pl": "—", "ru": "уставший", "category": "Sonstige"},
    {"de": "richtig", "pl": "—", "ru": "правильный, верно", "category": "Sonstige"},
    {"de": "schwarz", "pl": "—", "ru": "черный", "category": "Sonstige"},
    {"de": "sehr gut", "pl": "—", "ru": "очень хорошо", "category": "Sonstige"},
    {"de": "super", "pl": "—", "ru": "супер, отлично", "category": "Sonstige"},
    {"de": "toll", "pl": "—", "ru": "замечательный, классный", "category": "Sonstige"},
    {"de": "alt", "pl": "—", "ru": "старый", "category": "Sonstige"},
    {"de": "billig", "pl": "—", "ru": "дешевый", "category": "Sonstige"},
    {"de": "gebraucht", "pl": "—", "ru": "подержанный, б/у", "category": "Sonstige"},
    {"de": "kaputt", "pl": "—", "ru": "сломанный, разбитый", "category": "Sonstige"},
    {"de": "kurz", "pl": "—", "ru": "короткий", "category": "Sonstige"},
    {"de": "lang", "pl": "—", "ru": "длинный", "category": "Sonstige"},
    {"de": "modern", "pl": "—", "ru": "современный", "category": "Sonstige"},
    {"de": "neu", "pl": "—", "ru": "новый", "category": "Sonstige"},
    {"de": "praktisch", "pl": "—", "ru": "практичный", "category": "Sonstige"},
    {"de": "preiswert", "pl": "—", "ru": "недорогой, выгодный по цене", "category": "Sonstige"},
    {"de": "schön", "pl": "—", "ru": "красивый", "category": "Sonstige"},
    {"de": "teuer", "pl": "—", "ru": "дорогой", "category": "Sonstige"},
    {"de": "blau", "pl": "—", "ru": "синий, голубой", "category": "Sonstige"},
    {"de": "braun", "pl": "—", "ru": "коричневый", "category": "Sonstige"},
    {"de": "dünn", "pl": "—", "ru": "тонкий, худой", "category": "Sonstige"},
    {"de": "fein", "pl": "—", "ru": "мелкий, изысканный, отличный", "category": "Sonstige"},
    {"de": "gelb", "pl": "—", "ru": "желтый", "category": "Sonstige"},
    {"de": "grün", "pl": "—", "ru": "зеленый", "category": "Sonstige"},
    {"de": "rot", "pl": "—", "ru": "красный", "category": "Sonstige"},
    {"de": "süß", "pl": "—", "ru": "сладкий", "category": "Sonstige"},
    {"de": "geschieden", "pl": "—", "ru": "разведенный", "category": "Sonstige"},
    {"de": "groß", "pl": "—", "ru": "большой, высокий о росте", "category": "Sonstige"},
    {"de": "herzlich", "pl": "—", "ru": "душевный, сердечный", "category": "Sonstige"},
    {"de": "langweilig", "pl": "—", "ru": "скучный", "category": "Sonstige"},
    {"de": "ledig", "pl": "—", "ru": "холостой, не замужем", "category": "Sonstige"},
    {"de": "schwer", "pl": "—", "ru": "тяжелый", "category": "Sonstige"},
    {"de": "tot", "pl": "—", "ru": "мертвый", "category": "Sonstige"},
    {"de": "verheiratet", "pl": "—", "ru": "женат, замужем", "category": "Sonstige"},
    {"de": "bekannt", "pl": "—", "ru": "известный", "category": "Sonstige"},
    {"de": "bequem", "pl": "—", "ru": "удобный", "category": "Sonstige"},
    {"de": "berühmt", "pl": "—", "ru": "знаменитый", "category": "Sonstige"},
    {"de": "fremd", "pl": "—", "ru": "чужой, незнакомый", "category": "Sonstige"},
    {"de": "interessant", "pl": "—", "ru": "интересный", "category": "Sonstige"},
    {"de": "weit", "pl": "—", "ru": "далекий, далеко", "category": "Sonstige"},
    {"de": "hell", "pl": "—", "ru": "светлый", "category": "Sonstige"},
    {"de": "leise", "pl": "—", "ru": "тихий", "category": "Sonstige"},
    {"de": "möbliert", "pl": "—", "ru": "меблированный", "category": "Sonstige"},
    {"de": "ruhig", "pl": "—", "ru": "спокойный, тихий", "category": "Sonstige"},
    {"de": "sauber", "pl": "—", "ru": "чистый", "category": "Sonstige"},
    {"de": "warm", "pl": "—", "ru": "теплый", "category": "Sonstige"},
    {"de": "eignener/es/e", "pl": "—", "ru": "собственный", "category": "Sonstige"},
    {"de": "letzter/es/e", "pl": "—", "ru": "последний", "category": "Sonstige"},
    {"de": "persönlich", "pl": "—", "ru": "личный", "category": "Sonstige"},
    {"de": "angenehm", "pl": "—", "ru": "приятный", "category": "Sonstige"},
    {"de": "arbeitslos", "pl": "—", "ru": "безработный", "category": "Sonstige"},
    {"de": "anstrengend", "pl": "—", "ru": "утомляющий, тяжелый", "category": "Sonstige"},
    {"de": "beruflich", "pl": "—", "ru": "профессиональный", "category": "Sonstige"},
    {"de": "freundlich", "pl": "—", "ru": "дружелюбный", "category": "Sonstige"},
    {"de": "jung", "pl": "—", "ru": "молодой", "category": "Sonstige"},
    {"de": "selbstständig", "pl": "—", "ru": "самозанятый, независимый", "category": "Sonstige"},
    {"de": "sicher", "pl": "—", "ru": "безопасный, уверенный", "category": "Sonstige"},
    {"de": "üblich", "pl": "—", "ru": "обычный, привычный", "category": "Sonstige"},
    {"de": "zentral", "pl": "—", "ru": "центральный", "category": "Sonstige"},
    {"de": "zuverlässig", "pl": "—", "ru": "надежный", "category": "Sonstige"},
    {"de": "aktiv", "pl": "—", "ru": "активный", "category": "Sonstige"},
    {"de": "dick", "pl": "—", "ru": "толстый, полный", "category": "Sonstige"},
    {"de": "fit", "pl": "—", "ru": "в хорошей форме, бодрый", "category": "Sonstige"},
    {"de": "gesund", "pl": "—", "ru": "здоровый", "category": "Sonstige"},
    {"de": "heiß", "pl": "—", "ru": "горячий", "category": "Sonstige"},
    {"de": "krank", "pl": "—", "ru": "больной", "category": "Sonstige"},
    {"de": "regelmäßig", "pl": "—", "ru": "регулярный, регулярно", "category": "Sonstige"},
    {"de": "schlank", "pl": "—", "ru": "стройный", "category": "Sonstige"},
    {"de": "schlimm", "pl": "—", "ru": "плохой, тяжелый, сильный", "category": "Sonstige"},
    {"de": "ungesund", "pl": "—", "ru": "нездоровый", "category": "Sonstige"},
    {"de": "günstig", "pl": "—", "ru": "выгодный, недорогой", "category": "Sonstige"},
    {"de": "kalt", "pl": "—", "ru": "холодный", "category": "Sonstige"},
    {"de": "nass", "pl": "—", "ru": "мокрый, сырой", "category": "Sonstige"},
    {"de": "pünktlich", "pl": "—", "ru": "пунктуальный, вовремя", "category": "Sonstige"},
    {"de": "selten", "pl": "—", "ru": "редкий, редко", "category": "Sonstige"},
    {"de": "trocken", "pl": "—", "ru": "сухой", "category": "Sonstige"},
    {"de": "windig", "pl": "—", "ru": "ветреный", "category": "Sonstige"},
    {"de": "Auf Wiedersehen", "pl": "—", "ru": "до свидания", "category": "Sonstige"},
    {"de": "bitte", "pl": "—", "ru": "пожалуйста", "category": "Sonstige"},
    {"de": "Hallo!", "pl": "—", "ru": "привет!", "category": "Sonstige"},
    {"de": "man", "pl": "—", "ru": "неопределенно-личное местоимение", "category": "Sonstige"},
    {"de": "nein", "pl": "—", "ru": "нет", "category": "Sonstige"},
    {"de": "oder", "pl": "—", "ru": "или", "category": "Sonstige"},
    {"de": "aus", "pl": "—", "ru": "из", "category": "Sonstige"},
    {"de": "in", "pl": "—", "ru": "в", "category": "Sonstige"},
    {"de": "und", "pl": "—", "ru": "и", "category": "Sonstige"},
    {"de": "was", "pl": "—", "ru": "что", "category": "Sonstige"},
    {"de": "wer", "pl": "—", "ru": "кто", "category": "Sonstige"},
    {"de": "wie", "pl": "—", "ru": "как", "category": "Sonstige"},
    {"de": "wo", "pl": "—", "ru": "где", "category": "Sonstige"},
    {"de": "woher", "pl": "—", "ru": "откуда", "category": "Sonstige"},
    {"de": "aber", "pl": "—", "ru": "но", "category": "Sonstige"},
    {"de": "danke", "pl": "—", "ru": "спасибо", "category": "Sonstige"},
    {"de": "gern(e) / lieber", "pl": "—", "ru": "с удовольствием / лучше", "category": "Sonstige"},
    {"de": "hier", "pl": "—", "ru": "здесь", "category": "Sonstige"},
    {"de": "bis", "pl": "—", "ru": "до", "category": "Sonstige"},
    {"de": "ja", "pl": "—", "ru": "да", "category": "Sonstige"},
    {"de": "jetzt", "pl": "—", "ru": "сейчас", "category": "Sonstige"},
    {"de": "nicht", "pl": "—", "ru": "не", "category": "Sonstige"},
    {"de": "viel", "pl": "—", "ru": "много", "category": "Sonstige"},
    {"de": "von", "pl": "—", "ru": "от, из", "category": "Sonstige"},
    {"de": "alle", "pl": "—", "ru": "все", "category": "Sonstige"},
    {"de": "heute", "pl": "—", "ru": "сегодня", "category": "Sonstige"},
    {"de": "immer", "pl": "—", "ru": "всегда", "category": "Sonstige"},
    {"de": "je", "pl": "—", "ru": "когда-либо, по", "category": "Sonstige"},
    {"de": "kein", "pl": "—", "ru": "никакой", "category": "Sonstige"},
    {"de": "mehr", "pl": "—", "ru": "больше", "category": "Sonstige"},
    {"de": "prima", "pl": "—", "ru": "отлично, замечательно", "category": "Sonstige"},
    {"de": "sehr", "pl": "—", "ru": "очень", "category": "Sonstige"},
    {"de": "so", "pl": "—", "ru": "так, таким образом", "category": "Sonstige"},
    {"de": "wenig", "pl": "—", "ru": "мало", "category": "Sonstige"},
    {"de": "abends", "pl": "—", "ru": "по вечерам, вечером", "category": "Sonstige"},
    {"de": "danach", "pl": "—", "ru": "затем, после этого", "category": "Sonstige"},
    {"de": "gerade", "pl": "—", "ru": "прямо, сейчас в данный момент", "category": "Sonstige"},
    {"de": "gestern", "pl": "—", "ru": "вчера", "category": "Sonstige"},
    {"de": "halb", "pl": "—", "ru": "половина", "category": "Sonstige"},
    {"de": "mittags", "pl": "—", "ru": "в полдень", "category": "Sonstige"},
    {"de": "morgen", "pl": "—", "ru": "завтра", "category": "Sonstige"},
    {"de": "morgens", "pl": "—", "ru": "по утрам", "category": "Sonstige"},
    {"de": "zehn nach", "pl": "—", "ru": "десять минут после", "category": "Sonstige"},
    {"de": "nachmittags", "pl": "—", "ru": "после обеда, днем", "category": "Sonstige"},
    {"de": "nachts", "pl": "—", "ru": "ночью, по ночам", "category": "Sonstige"},
    {"de": "um zwölf", "pl": "—", "ru": "в 12 часов", "category": "Sonstige"},
    {"de": "von ... bis ...", "pl": "—", "ru": "с ... до ...", "category": "Sonstige"},
    {"de": "Viertel vor", "pl": "—", "ru": "без четверти", "category": "Sonstige"},
    {"de": "vormittags", "pl": "—", "ru": "до обеда, в первой половине дня", "category": "Sonstige"},
    {"de": "etwas", "pl": "—", "ru": "что-то, немного", "category": "Sonstige"},
    {"de": "nichts", "pl": "—", "ru": "ничего", "category": "Sonstige"},
    {"de": "zu viel", "pl": "—", "ru": "слишком много", "category": "Sonstige"},
    {"de": "zu wenig", "pl": "—", "ru": "слишком мало", "category": "Sonstige"},
    {"de": "geboren", "pl": "—", "ru": "рожденный", "category": "Sonstige"},
    {"de": "leider", "pl": "—", "ru": "к сожалению", "category": "Sonstige"},
    {"de": "manchmal", "pl": "—", "ru": "иногда", "category": "Sonstige"},
    {"de": "schade", "pl": "—", "ru": "жаль", "category": "Sonstige"},
    {"de": "später", "pl": "—", "ru": "позже", "category": "Sonstige"},
    {"de": "vorgestern", "pl": "—", "ru": "позавчера", "category": "Sonstige"},
    {"de": "dort", "pl": "—", "ru": "там", "category": "Sonstige"},
    {"de": "gegenüber", "pl": "—", "ru": "напротив", "category": "Sonstige"},
    {"de": "geradeaus", "pl": "—", "ru": "прямо", "category": "Sonstige"},
    {"de": "mehrere", "pl": "—", "ru": "несколько", "category": "Sonstige"},
    {"de": "ungefähr", "pl": "—", "ru": "приблизительно", "category": "Sonstige"},
    {"de": "wohin", "pl": "—", "ru": "куда", "category": "Sonstige"},
    {"de": "dazu", "pl": "—", "ru": "к этому, кроме того", "category": "Sonstige"},
    {"de": "etwa", "pl": "—", "ru": "около, примерно", "category": "Sonstige"},
    {"de": "netto", "pl": "—", "ru": "нетто, чистыми", "category": "Sonstige"},
    {"de": "sofort", "pl": "—", "ru": "сразу, немедленно", "category": "Sonstige"},
    {"de": "verboten", "pl": "—", "ru": "запрещено", "category": "Sonstige"},
    {"de": "zurzeit", "pl": "—", "ru": "в настоящее время", "category": "Sonstige"},
    {"de": "bald", "pl": "—", "ru": "скоро", "category": "Sonstige"},
    {"de": "dieser/es/e", "pl": "—", "ru": "этот", "category": "Sonstige"},
    {"de": "einfach", "pl": "—", "ru": "просто", "category": "Sonstige"},
    {"de": "genauso", "pl": "—", "ru": "аналогично, так же", "category": "Sonstige"},
    {"de": "wieder", "pl": "—", "ru": "снова", "category": "Sonstige"},
    {"de": "wirklich", "pl": "—", "ru": "действительно", "category": "Sonstige"},
    {"de": "brutto", "pl": "—", "ru": "брутто, до вычета налогов", "category": "Sonstige"},
    {"de": "deshalb", "pl": "—", "ru": "поэтому", "category": "Sonstige"},
    {"de": "einverstanden", "pl": "—", "ru": "согласен", "category": "Sonstige"},
    {"de": "gleich", "pl": "—", "ru": "сейчас, сразу, одинаковый", "category": "Sonstige"},
    {"de": "hoffentlich", "pl": "—", "ru": "надеюсь", "category": "Sonstige"},
    {"de": "möglich", "pl": "—", "ru": "возможный", "category": "Sonstige"},
    {"de": "nie", "pl": "—", "ru": "никогда", "category": "Sonstige"},
    {"de": "sogar", "pl": "—", "ru": "даже", "category": "Sonstige"},
    {"de": "genug", "pl": "—", "ru": "достаточно", "category": "Sonstige"},
    {"de": "mindestens", "pl": "—", "ru": "как минимум, по крайней мере", "category": "Sonstige"},
    {"de": "stündlich", "pl": "—", "ru": "каждый час, ежечасно", "category": "Sonstige"},
    {"de": "übermorgen", "pl": "—", "ru": "послезавтра", "category": "Sonstige"},
    {"de": "ab wann", "pl": "—", "ru": "с какого времени, с каких пор", "category": "Sonstige"},
    {"de": "(in) bar", "pl": "—", "ru": "наличными", "category": "Sonstige"},
    {"de": "einige", "pl": "—", "ru": "некоторые, несколько", "category": "Sonstige"},
    {"de": "hin und zurück", "pl": "—", "ru": "туда и обратно", "category": "Sonstige"}
];

// Перемешивание карточек (Fisher–Yates)
function shuffleWords(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}